### ISSUE TITLE
"Open from browser" raises error

### ISSUE THREAD

**Issue by esevan** [zhfjyq/vscode-plugin-drawio#7]
Hi, thanks for the great extension.

I have been using this extension for more than 3 months.
Since maybe last month, "Open from browser" in drawio window have been raising `Caanot read property 'setConsumer' of undefined` error as below. So only "Open recent" menu is available...
![image](https://user-images.githubusercontent.com/8223765/87736115-458c2380-c812-11ea-84f9-7eec14c804a9.png)

Also, every time I try to open the extension from `.md` file, I see chrome is started from `about:blank` page with restore warning.
![image](https://user-images.githubusercontent.com/8223765/87736595-7f115e80-c813-11ea-9e18-a7ce60f4110e.png)

I'm using chrome 83.0.4103.116 64 bit version.
Can I have any clue to resolve this issue?

**Comment by zhfjyq** [comment]
thanks for you using my extension, and now , a new and better extension in vscode is named “draw.io integration” is easier for use, I use it now. You may try it




| |
ZhuFeng
邮箱：zhfjyq@163.com
|

Signature is customized by Netease Mail Master

On 07/17/2020 08:47, Eunsoo Park (Evan) wrote:

Hi, thanks for the great extension.

I have been using this extension for more than 3 months.
Since maybe last month, "Open from browser" in drawio window have been raising Caanot read property 'setConsumer' of undefined error as below. So only "Open recent" menu is available...


I'm using chrome 83.0.4103.116 64 bit version.
Can I have any clue to resolve this issue?

**Comment by esevan** [comment]
> thanks for you using my extension, and now , a new and better extension in vscode is named “draw.io integration” is easier for use, I use it now. You may try it | | ZhuFeng 邮箱：zhfjyq@163.com | Signature is customized by Netease Mail Master On 07/17/2020 08:47, Eunsoo Park (Evan) wrote: Hi, thanks for the great extension. I have been using this extension for more than 3 months. Since maybe last month, "Open from browser" in drawio window have been raising Caanot read property 'setConsumer' of undefined error as below. So only "Open recent" menu is available... I'm using chrome 83.0.4103.116 64 bit version. Can I have any clue to resolve this issue? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

OK... I actually use it as well, but the main complaint is it only supports "embed" to export my drawing.
The "export as PNG" support was what I expected from the drawio extension. Anyway, thanks for reply very quickly :)
